-- schema-javadb.sql
-- DDL commands for JavaDB/Derby
CREATE TABLE MOVIE (
  ID             INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  NAME           VARCHAR(70),
  YEAROFRELEASE  INT,
  CLASSIFICATION VARCHAR(50),
  DESCRIPTION    VARCHAR(500),
  LOCATION       VARCHAR(120)
);

CREATE TABLE CUSTOMER (
  ID          INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  NAME        VARCHAR(50),
  DATEOFBIRTH DATE,
  ADDRESS     VARCHAR(150),
  EMAIL       VARCHAR(50),
  PHONENUMBER VARCHAR(20)
);

CREATE TABLE LEASES (
  ID              INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  MOVIEID              INT REFERENCES MOVIE (ID) ON DELETE CASCADE,
  CUSTOMERID           INT REFERENCES CUSTOMER (ID) ON DELETE CASCADE,
  PRICE                INT,
  DATEOFRENT           DATE,
  EXPECTEDDATEOFRETURN DATE,
  DATEOFRETURN         DATE
);