  -- schema-psql.sql
  -- DDL commands for PostgreSQL
  DROP TABLE IF EXISTS LEASE;
  DROP TABLE IF EXISTS CUSTOMER;
  DROP TABLE IF EXISTS MOVIE;

 CREATE TABLE MOVIE (
   ID             SERIAL PRIMARY KEY,
   NAME           VARCHAR,
   YEAROFRELEASE  INT,
   CLASSIFICATION VARCHAR,
   DESCRIPTION    VARCHAR,
   LOCATION       VARCHAR);

 CREATE TABLE CUSTOMER (
   ID          SERIAL PRIMARY KEY,
   NAME        VARCHAR,
   DATEOFBIRTH DATE,
   ADDRESS     VARCHAR,
   EMAIL       VARCHAR,
   PHONENUMBER VARCHAR);

 CREATE TABLE LEASES (
   ID              SERIAL PRIMARY KEY,
   MOVIEID              INT REFERENCES MOVIE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
   CUSTOMERID           INT REFERENCES CUSTOMER (ID) ON DELETE CASCADE ON UPDATE CASCADE,
   PRICE                INT,
   DATEOFRENT           DATE,
   EXPECTEDDATEOFRETURN DATE,
   DATEOFRETURN         DATE);