-- my-test-data.sql

INSERT INTO MOVIE (NAME, YEAROFRELEASE, CLASSIFICATION, DESCRIPTION, LOCATION) VALUES ('Propadak',2000,'21+','Worst movie ever.','doma');

INSERT INTO MOVIE (NAME, YEAROFRELEASE, CLASSIFICATION, DESCRIPTION, LOCATION) VALUES ('Nejlepsi',1994,'4+','Best movie ever.','u suseda');

INSERT INTO CUSTOMER (NAME, DATEOFBIRTH, ADDRESS, EMAIL, PHONENUMBER) VALUES ('Pepa Nový','2013-04-01','Pepova 12, Pepov','pepa@gmail.com', '112');

